"use client";

import { useState } from "react";
import ProjectForm from "./ProjectForm";
import ProjectCard from "./ProjectCard";

interface Project {
  id: number;
  title: string;
  githubUrl: string;
  category: string;
}

const ProjectsSection = () => {
  const [projects, setProjects] = useState<Project[]>([]);

  const handleProjectSubmit = (project: { title: string; githubUrl: string; category: string }) => {
    // Create a new project with an autogenerated id
    const newProject = {
      id: Date.now(), // Simple way to generate a unique ID
      ...project,
    };

    setProjects([newProject, ...projects]); // Adds the new project to the list
  };

  return (
    <section className="py-12 px-6 bg-gray-100 dark:bg-black min-h-screen">
      <h2 className="text-3xl font-bold text-center text-gray-900 dark:text-white mb-8">
        Share Your Project
      </h2>
      
      {/* Project Submission Form */}
      <div className="flex justify-center">
        <ProjectForm onSubmit={handleProjectSubmit} />
      </div>

      {/* Display Project Cards */}
      <div className="mt-10 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 justify-center">
        {projects.length === 0 ? (
          <p className="text-center text-gray-600 dark:text-gray-400">No projects submitted yet.</p>
        ) : (
          projects.map((project) => (
            <ProjectCard
              key={project.id}
              title={project.title}
              githubUrl={project.githubUrl}
              category={project.category}
            />
          ))
        )}
      </div>
    </section>
  );
};

export default ProjectsSection;
